<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//span[@class='ajax_block_cart_total']</description>
   <name>lblTotalCost</name>
   <tag></tag>
   <elementGuidId>fe15697e-eb0c-404d-82fd-2cd9a9079794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='ajax_block_cart_total']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
