<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CSV_ValidationFailed</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>065f8b11-c0e9-42b9-9513-f9aa31d5fe6f</testSuiteGuid>
   <testCaseLink>
      <guid>937e9b28-f5e6-485c-84ad-ecd5ba58bce1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ThaiLeM-Day4/ValidationFailed</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2fc878e3-7803-48bd-9899-c91e73b315ac</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CSV_ValidationFailed</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>2fc878e3-7803-48bd-9899-c91e73b315ac</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>4f8c9c24-0b50-4d6f-8471-ade98ba73dce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2fc878e3-7803-48bd-9899-c91e73b315ac</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>237a1daa-b4e9-41ec-9eaf-e878ffb40cb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2fc878e3-7803-48bd-9899-c91e73b315ac</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>errorMsg</value>
         <variableId>8e578efd-c1ca-450d-8f99-df4bbf8b4e6b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
