<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Excel_HaDangT_Day4_Practice1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a6ee5050-f59f-4d5d-89c0-6d61e5a86251</testSuiteGuid>
   <testCaseLink>
      <guid>1acb5efd-4296-4584-8071-0f0c63fe0c98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HaDangT_Day4_Practice1-2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>32b6ee0c-0aef-4aac-ace9-8364e58fc836</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Excel_HaDangT_Day4_Practice1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>32b6ee0c-0aef-4aac-ace9-8364e58fc836</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>a91f0e66-17fb-4dc7-8386-77807b5f7e21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>32b6ee0c-0aef-4aac-ace9-8364e58fc836</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>7972f1a8-3402-4de9-adba-e52375fade55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>32b6ee0c-0aef-4aac-ace9-8364e58fc836</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>errorMsg</value>
         <variableId>5675af96-3f9d-49b5-a9fa-abc0f0704dd6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
