<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>HaDangT_Day3_EX03</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>20aa5ba9-8365-4cc5-820b-ff6a1805ae51</testSuiteGuid>
   <testCaseLink>
      <guid>8880eec6-86c0-4fdb-a225-ceaaf2c8a559</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HaDangT_Day3_EX03/EX03-01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd84516e-8ca6-42d7-9515-fcdc2b1c5abe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee127e54-ae29-4e5b-92cf-3ec8efeed613</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HaDangT_Day3_EX03/EX03-02</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37d80838-9f2a-42fe-b2d9-d0768ad39fb9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec8339b9-8f90-4d88-af0d-b44dda1676b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HaDangT_Day3_EX03/EX03-03</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc6ae11c-aa73-4135-a3e3-2c7dd69cabeb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
