<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ID_HaDangT_Day4_Practice1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d4902b5d-da93-430f-bcb0-590caa6edaf3</testSuiteGuid>
   <testCaseLink>
      <guid>f8e79efa-63b6-4962-9d89-cc8323cdc08d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HaDangT_Day4_Practice1-2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8b85b0cc-4f01-4a5d-87e9-b85ef1f710d4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ID_HaDangT_Day4_Practice1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>8b85b0cc-4f01-4a5d-87e9-b85ef1f710d4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>a91f0e66-17fb-4dc7-8386-77807b5f7e21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8b85b0cc-4f01-4a5d-87e9-b85ef1f710d4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>7972f1a8-3402-4de9-adba-e52375fade55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8b85b0cc-4f01-4a5d-87e9-b85ef1f710d4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>errorMessage</value>
         <variableId>5675af96-3f9d-49b5-a9fa-abc0f0704dd6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
