<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ID_SuccessfullyLogin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>9f2952d2-3a86-4eb9-8b0b-4e6502f6bccd</testSuiteGuid>
   <testCaseLink>
      <guid>d4c9f2db-e475-4a0c-9226-65d70f96fd1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ThaiLeM-Day4/SuccessfullyLogin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d7439ae5-f5d3-4d60-a9db-d04b83a2a0e1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ID_SuccessfullyLogin</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d7439ae5-f5d3-4d60-a9db-d04b83a2a0e1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>cd4424c8-dd16-4163-ac9b-29a15d54311e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d7439ae5-f5d3-4d60-a9db-d04b83a2a0e1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>6686ab4b-2c32-4186-bec2-904082937f8f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
