<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Practice2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>79c736e3-8c51-4278-af31-ec1ca4f6c0c5</testSuiteGuid>
   <testCaseLink>
      <guid>ed122187-acfb-407b-a2b1-c8be8a333c09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lesson4/Login Failed</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>af9d33fd-f2f4-4d06-9aed-a09f36c6ccc1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Lesson4/Practice2</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>af9d33fd-f2f4-4d06-9aed-a09f36c6ccc1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>33fd3030-7355-4533-be16-dee8c71ba597</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af9d33fd-f2f4-4d06-9aed-a09f36c6ccc1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>84602de3-c297-458d-8279-6ec416cfb54f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af9d33fd-f2f4-4d06-9aed-a09f36c6ccc1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>errorMsg</value>
         <variableId>d357e94f-ce17-4f18-9630-0519527a23b6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
