<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DanhPhamC_Day4_Practice3_Excelfile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a55769b6-c6dc-478a-9e37-80c1f13625e3</testSuiteGuid>
   <testCaseLink>
      <guid>7c84a77b-d929-4930-9ea4-7730b7eeccaf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lesson4/DanhPhamC_Day4_Practice3</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9a451ddc-261d-4ecc-ab3d-cbdcfd4ecb95</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DanhPhamC_Day4_Practice3/ExcelFile</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>9a451ddc-261d-4ecc-ab3d-cbdcfd4ecb95</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>51c1df7d-6d54-446c-a43b-ee0c82341baf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9a451ddc-261d-4ecc-ab3d-cbdcfd4ecb95</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>1b8143e3-4a05-4f8a-b65a-20070f21883c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9a451ddc-261d-4ecc-ab3d-cbdcfd4ecb95</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>success</value>
         <variableId>bf880b10-e3d3-4e04-9ede-b2583255b594</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
