<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Csv</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f60fa1e1-15ad-4ac2-812e-c62f651f4495</testSuiteGuid>
   <testCaseLink>
      <guid>9f84d45d-5792-44c5-8ae5-cf4f0976ddc1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/lession4/HanhNguyenT_Day4_LoginPass</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7b207d95-ea5e-4d55-b0f2-0a71b5e15606</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ex03_csv</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>7b207d95-ea5e-4d55-b0f2-0a71b5e15606</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>8dd9e8e4-676e-4229-baa5-9ae770cdf57e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7b207d95-ea5e-4d55-b0f2-0a71b5e15606</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c6895c73-e544-4dd2-b201-a50e8a7b7ef7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
