<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>EX03-CSV</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2ea02743-cf00-4781-a9ac-bb7222e319b8</testSuiteGuid>
   <testCaseLink>
      <guid>6527c8b5-5521-442b-846d-5eaf2cd32b92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/EX03-Successfully login/EX03_01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>07545c4a-d36a-4223-ba29-0b2efb86b9b6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/EX03/EX03-CSV</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a3fecc8-743c-4d43-8fc0-fb500805ebb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>615bd187-5d65-4670-97ce-d5870b0981e0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
