<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_EX03_Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>82d0ae3b-9c91-4a77-a8ef-d075714bcd7f</testSuiteGuid>
   <testCaseLink>
      <guid>ad8979d7-b18d-4fc5-b0cd-be8c29e6b194</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/lesson4/chungphamv_Day4_LoginSuccessfully</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>20195a74-efb6-4cb6-a5e2-8e4fdaaaa190</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/EX03_LoginSuccessfully/DF_EXO3_Excel</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>20195a74-efb6-4cb6-a5e2-8e4fdaaaa190</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>1237bb2d-7fbc-41e8-81d5-cd95c0f49fbd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>20195a74-efb6-4cb6-a5e2-8e4fdaaaa190</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>be51bd98-457b-40a5-9d84-bdfa1d254cf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>20195a74-efb6-4cb6-a5e2-8e4fdaaaa190</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>message</value>
         <variableId>39883e28-450a-4c49-9d95-006cdddcc9cf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
