<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Checkout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e2fa14cf-69ba-4ae0-ad43-029cca9cdb66</testSuiteGuid>
   <testCaseLink>
      <guid>f29adaa6-347a-42f2-be81-860591b59c1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lesson3/Checkout/EX02-02_AddToCart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8baa2c5b-2dd7-4b01-b373-a22431d362de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81034b20-1135-4e69-a9ad-ee3e740e07ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52462bbe-9d26-47d8-bc3f-5f466ed33e07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lesson3/Checkout/EX02-01_CreateAccount</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53f3bb39-8a98-42c5-ae9c-8f370ee342c6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
