<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Searching</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d5be1290-277c-4776-993d-44561f9c8f84</testSuiteGuid>
   <testCaseLink>
      <guid>f610ce88-6f9f-4aba-996b-0e7e77e06ec3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lesson3/Searching/EX03-01_SearchNoResult</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd2e557f-3e62-409f-a6ad-34d540721c5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64b75a7a-a374-43a0-bf47-ad38043aded8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>090894fe-0187-4ad5-8491-5739018cf97b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lesson3/Searching/EX03-03_CheckContainsKeyword</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf32a1ee-0b54-4fce-bde9-236e96953fad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c6afaeb-dac1-4e2d-b698-9329797911e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c26cbef9-a099-47e3-87fa-2e68d0ebe4fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41d2cd6d-e8df-4aad-8a5b-49d5b0b43e0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45e53433-5352-4fb3-aeb2-3cd4c6983518</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3684ad0d-444b-452a-b63d-0917cf49a94d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af044c6a-e88b-4893-898f-07698fbc2b66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lesson3/Searching/EX03-02_SearchHaveResult</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d04b649-b42a-4fbb-ba25-ef8122b5c7e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b7434f2-deb1-486b-9f06-74a5f1567a2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b80b13d-42bc-44d2-bb51-8d2d347ddbe6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e674b603-004e-4646-bf14-847d97bfc16a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99cdfe6f-02e0-4145-8574-9a9bbd18478d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0a0f427-bdf0-4e19-8951-52c75ab2b9bd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
