<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>EX01-Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>331bdd0a-70c5-4af2-b3dc-cdfbcce55675</testSuiteGuid>
   <testCaseLink>
      <guid>975a222e-895d-4993-a522-eb8180001acd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Ex01-Validation failed/EX01_01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8814943d-ec98-4046-a0e4-74bd56fa0d6c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/EX01/EX01-Excel</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8c2b9ec-781e-48fa-880b-d877042f977f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>672229b2-6fc4-40bc-af52-9238aef25bc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>130f4784-0c6e-48e3-b833-69fab08b9234</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
