<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Success_Login_CSV</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>5946f979-3b75-4074-a80b-bec211e8a31c</testSuiteGuid>
   <testCaseLink>
      <guid>0aaa9065-fa09-4759-8f71-d91e634c76cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lesson4/Login/Ex03_LoginSuccess</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>13aadafb-96bf-44cd-9456-f863231d93c4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Success/Success_Login_CSV</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>13aadafb-96bf-44cd-9456-f863231d93c4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>f49fe786-a775-43e8-a024-25233215e5f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>13aadafb-96bf-44cd-9456-f863231d93c4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>8f71f64f-350d-4e3a-9dde-3d931167ceac</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
