<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Practice1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4f5a6294-4e4f-42a8-9649-c752b11565f6</testSuiteGuid>
   <testCaseLink>
      <guid>dcad82a2-2fb9-483b-8437-482b4c0e6d74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lesson3/Practice1/Practice1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5ee6826-a7a3-42c6-8e0c-4cd616c111ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86001268-55b1-48c0-9cc1-02f3b39b6ebd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
